# Generated by Django 5.2.16 on 2026-07-18 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='origem',
            field=models.CharField(choices=[('INTERNO', 'Criado pela barbearia'), ('ONLINE', 'Agendamento on-line')], default='INTERNO', max_length=10),
        ),
        migrations.CreateModel(
            name='BloqueioAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=160)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios_agenda', to='gestao.barbearia')),
                ('profissional', models.ForeignKey(limit_choices_to={'papel': 'BARBEIRO'}, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios_agenda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bloqueio de agenda',
                'verbose_name_plural': 'bloqueios de agenda',
                'ordering': ['inicio'],
                'indexes': [models.Index(fields=['profissional', 'inicio', 'fim'], name='gestao_bloq_profiss_58dc8a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='bloqueio_agenda_fim_apos_inicio')],
            },
        ),
        migrations.CreateModel(
            name='HorarioTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_trabalho', to='gestao.barbearia')),
                ('profissional', models.ForeignKey(limit_choices_to={'papel': 'BARBEIRO'}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_trabalho', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'horário de trabalho',
                'verbose_name_plural': 'horários de trabalho',
                'ordering': ['profissional', 'dia_semana', 'inicio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='horario_trabalho_fim_apos_inicio'), models.UniqueConstraint(fields=('profissional', 'dia_semana', 'inicio', 'fim'), name='horario_trabalho_sem_duplicidade')],
            },
        ),
    ]
