# Generated by Django 5.2.16 on 2026-07-18 21:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_normalizar_telefones'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='comissao_percentual_aplicada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='comissao_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='concluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('CARTAO_DEBITO', 'Cartão de débito'), ('CARTAO_CREDITO', 'Cartão de crédito'), ('PENDENTE', 'Pagamento pendente')], max_length=20),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='iniciado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('CONFIRMADO', 'Confirmado'), ('EM_ATENDIMENTO', 'Em atendimento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('FALTOU', 'Cliente faltou')], default='AGENDADO', max_length=15),
        ),
    ]
