# Generated by Django 5.2.16 on 2026-07-18 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_preencher_historico_financeiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='aceita_notificacoes_whatsapp',
            field=models.BooleanField(default=False, verbose_name='Aceita notificações pelo WhatsApp'),
        ),
        migrations.CreateModel(
            name='NotificacaoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONFIRMACAO', 'Confirmação do agendamento'), ('LEMBRETE_24H', 'Lembrete de 24 horas'), ('LEMBRETE_2H', 'Lembrete de 2 horas')], max_length=20)),
                ('destinatario', models.CharField(max_length=20)),
                ('agendada_para', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIANDO', 'Enviando'), ('ENVIADA', 'Enviada'), ('FALHOU', 'Falhou'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=12)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('mensagem_id', models.CharField(blank=True, max_length=255)),
                ('ultimo_erro', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_whatsapp', to='gestao.agendamento')),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_whatsapp', to='gestao.barbearia')),
            ],
            options={
                'verbose_name': 'notificação do WhatsApp',
                'verbose_name_plural': 'notificações do WhatsApp',
                'ordering': ['agendada_para'],
                'indexes': [models.Index(fields=['status', 'agendada_para'], name='gestao_noti_status_20cfce_idx'), models.Index(fields=['barbearia', 'status'], name='gestao_noti_barbear_6e1065_idx')],
                'constraints': [models.UniqueConstraint(fields=('agendamento', 'tipo'), name='whatsapp_tipo_unico_por_agendamento')],
            },
        ),
    ]
