# Generated by Django 5.2.16 on 2026-09-05 00:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import gestao.models
from datetime import timedelta
from decimal import Decimal
from django.db import migrations, models


def criar_testes_para_barbearias_existentes(apps, schema_editor):
    Assinatura = apps.get_model("gestao", "Assinatura")
    Barbearia = apps.get_model("gestao", "Barbearia")
    agora = django.utils.timezone.now()
    fim_teste = agora + timedelta(days=7)
    Assinatura.objects.bulk_create(
        [
            Assinatura(
                barbearia=barbearia,
                status="TESTE",
                inicio_teste=agora,
                fim_teste=fim_teste,
            )
            for barbearia in Barbearia.objects.all()
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_pagina_publica_e_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('codigo', models.SlugField(max_length=60, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=180)),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('limite_profissionais', models.PositiveSmallIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'plano',
                'verbose_name_plural': 'planos',
                'ordering': ['ordem', 'valor_mensal', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TESTE', 'Período de teste'), ('ATIVA', 'Ativa'), ('INADIMPLENTE', 'Inadimplente'), ('SUSPENSA', 'Suspensa'), ('CANCELADA', 'Cancelada'), ('ISENTA', 'Liberada manualmente')], default='TESTE', max_length=15)),
                ('inicio_teste', models.DateTimeField(default=django.utils.timezone.now)),
                ('fim_teste', models.DateTimeField(default=gestao.models.fim_teste_padrao)),
                ('inicio_assinatura', models.DateTimeField(blank=True, null=True)),
                ('fim_periodo_atual', models.DateTimeField(blank=True, null=True)),
                ('suspensa_em', models.DateTimeField(blank=True, null=True)),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('gateway', models.CharField(blank=True, max_length=30)),
                ('identificador_externo', models.CharField(blank=True, max_length=160)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('barbearia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='gestao.barbearia')),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='gestao.plano')),
            ],
            options={
                'verbose_name': 'assinatura',
                'verbose_name_plural': 'assinaturas',
                'ordering': ['-criada_em'],
                'indexes': [models.Index(fields=['status', 'fim_teste'], name='gestao_assi_status_0eafac_idx')],
            },
        ),
        migrations.RunPython(
            criar_testes_para_barbearias_existentes,
            migrations.RunPython.noop,
        ),
    ]
